language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: FbbKcdlVTsuiML7mTdQJiQIH6FQl0FyxBiBZMQAsn/vJ7rfVCU3+QstelnSZBktOtUvlRSgxXzfE7PGHEAHGpfPzVN2MYQKhxho0hBxyNggRTE+9VA7LNFOq9zftGaoxiX++pSNOVGsG/D75nROVIxSBSKFHp9lvDQauI0ixsRnr18afgG3K9X79+xrMw/waDYKYRsDG1MGDYOXjpVmvJK5w3lFR3NJNL8E6mL1sFCGMwCKCd8BJ1xDGD1MFcYAftFJnW4QfXjse7B+GfJ6/kmkDAcGGkppQGd7AgjTwh0vBd5o7xX1o4q9mbAOeFRdXUcJf7qpSj08cVuZ8deSu3V6JShSrP2wqBiotLP0SPkUc3bJqxxv0CIbiUva86KJJD3V1wly/BgRQ8kd0tLIOj1ozgkO02trUjbhbGiaw4xqQTiJOAvL2w9mkYx1kR0rLQ6ZBj1sDoFwdRsl8gWg8eh1+NpaQxLYKepSHQsh5bU+IDqb2Nc4CMcAY5dUEHN7dWT+8guBIiw0F3z+CKT4nE9QRelzEWFstLZufJGFgaZrg5pT5xHNvJaRITuLQj0jqbJKY9E5w0fUnDqChyDqxnWju8TE9TDYI8YAGX118lZFv1lKpb4SuXeNoz905k4SndGzmuLpc2ym4PeM9rmVj2Mcg0p490ve+s8Yjslpvbgk=
    # FIREBASE_SECRET
    - secure: vKBeS9cvrva9lb2+xftyb3HsQnqn3A7e9f9hTB0Iz+sOMAkH+NuUdVwpYj2xdqqmik9ccTvX/wZftlhWc9cfwbmlxXQ1eS+q4XYxa3yjVjJWyyjwO127vLQi2M2+fEM/jE/sD6fphMmfW/Z0/yYDe2mQvN5q8+sFDf1eBrwh2r5PIPdPBmIzkAtTdchWhSKJCv6bfv0eMbHx2oqhQvHsTQbXK7kl0lMjb3p6h3O5xBMxX0ioyzwwaFZYdJsIlayXtuXMa7AtTTzdv4GoTpd8xejlgxwzEyUqvpQDo2KKM9g7DFsjzXUuWGYr894kVYL4lvYQ1e1z7+4UMHZrGbhtidbROXrgW8IyLs1HRPa9nMHo+gKVR/+pOEZaWpFqveVBh5rBMjms3TU4ziZxU1DDPBiApzxzjjV8tDjX2JDkSlLfS2H/VhvF3EuWYwjgcOWDH6/vVHfc+lt8KIDSa0/lWLZ47UjKF9Q2I18BQOfQnYnC5f14wLEeVC33XkGntvJ4KltSJtoCy7BH1JXX1TIa2dgEx8gnzYGJS30jfRXsC/32F3HNhJ/5AopU2d+Djv/OAg4toinNXHBmGveZiID/fyBNVPw6UHINmw/7J+O1Eo9B95nMcTNVui+LUIEyqCQmgldF6FDjEIsarT58sf3EDKSifE55yJhizCo08RqjjKw=
