language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: tQj35XBgB6SDSG8AY3HKQ7rZWKHb3p2QwPJOzx6FWUG/4uygvC0qqI2uyFAi2RuCldaN/IxpqAa6oCJSkdKIDS4vSsYsryLOj8mDNAmV6UdSp3Zld3kHxEfviA1G57SQUnIPYVWmGUM1L9hsJK5q363l4Q+5KYwVUqnnz880OmnAtD0aOPX+DTQTCHQjyDkQGzQFzdlnOD4T9x4fkaDrm2Akb1uSlclPz06cJBkygztZ8uxMvmKBdT5WLByJNuYIZnP/u+P+jnln/OFHEPj+pyVP8OixP9zAJjtEOxXubrE5sxyDpf6NQJWpb+WcAKNxslpSUd3RMtqRcnV4KF1Ht/ddklImUottzRImGwgVPz8uh3v+Z1yhKDvseHxsXre6dLTSxVtSl9vnJZGPnn/g5d6aN4fphkKTLbWscYp5qMHg4ByBFrFqKLFL3+SvX+gjfsoYKGPmJsaS1Gp+ZbIiD7/LOETUJOX3PALisrW7qWree+TU3T5RG9Cvu7A9QQgm4djb46lnzhhg9n17Y46sHaCYzuCjll33Ya7nNSbRBlOPT46f58xjGUU/xJ40bkJ1Y6CPxQvI5jJ75k7efMMJJUcb2Va13wYJiZtPHDnraOhTTCRqB3PIiedPbUcqBhgSM7kCY/uVtKLvRRjP1nlhEf9lHyBaZhxYd5u9aAMBCL8=
    # FIREBASE_SECRET
    - secure: Wd0lyUQil8jCAeNO5T26Mmu7yWwmnwnIkkADeojjK5PbwmudWNzLUZ8o2GDoR/TGhO4VGzo+0WSD23Bvb2x0mu/LHMQVTDBXU+FKsDNObuMwfoea3lsmu3u1TUj2H1K3X8N+gcX5l2XJaPAMhwFLWkNzc0u02A5NDmhr/4n0VXgCyQB/3LxvK38OmnPd0TwHHeLavUan0/fdwJwrvucK9l+pCt56m2aYwc8TyT1bcTtGP75Fg1zzcDiSkz+jRc5Zl+SRaEktgwmwTZY3A+AubalPOGp42NLWMP4NR5WOX9BmasYsrogh1UH0iLZYJaps2+XT7j2CfTFD5dgRRIp9qrmyU9D+/qwIlZk+YdUhUUAGQQ+sVP9PSy4oqDdvKpmZUfSmk/Z7X3QbmYQDCzDCegL9QWNyOq50QDo4WXPg1WclgdPbjc9LDVcfU/2pzzqi9+LHn7N3R3bvCr6vHfygcjpqL8Nb/7DTHyCegWsi6L1ZPMOJo/IO9R4sqS4zfJsaVEDONWqZ+GzRnpoeMovsGlQP9lHccdgbfauyxUANbgRSVoQ7Mi7l2e1HSp+q2AGkb97SKPKU86nYxs7E2u98FTmTMGplQW2FGvR+CtaigBdMPBofVgZiUfEUI+4DXOrx2bUIJBiqWlZ+fMYWWsww8PxXfTOW5qrnDqHMF8qmdOY=
